# PyTorch

It is another library equivalent to tensorflow developed by facebook. It uses power of GPU. 
It is python based library. 



In [107]:
# installation instructions on https://pytorch.org/get-started/locally/

from __future__ import print_function
import torch.cuda

In [108]:
torch.__version__

'2.0.1+cpu'

In [109]:
torch.cuda.is_available()


False

### construct 6X3 matrix . uninitialized

In [49]:
a = torch.empty(6,3)
print(a)

tensor([[1.0194e-38, 9.9184e-39, 2.9389e-39],
        [1.0194e-38, 2.9389e-39, 9.2755e-39],
        [9.0918e-39, 1.0010e-38, 9.9184e-39],
        [1.0653e-38, 9.1837e-39, 9.6428e-39],
        [1.0010e-38, 9.1837e-39, 8.9082e-39],
        [9.2755e-39, 1.1112e-38, 0.0000e+00]])


### construct 6X3 random

In [50]:
a = torch.rand(4,3)
a

tensor([[0.5148, 0.9054, 0.6871],
        [0.1095, 0.9694, 0.2845],
        [0.7305, 0.2005, 0.5813],
        [0.1571, 0.8405, 0.8382]])

### Construct zeros matrix

In [51]:
a = torch.zeros(4,3 , dtype = torch.long)
print(a)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### construct a tensor with data :

In [52]:
a = torch.tensor([7.8 , 5]) # convert list into tensor
a

tensor([7.8000, 5.0000])

In [53]:
type(a)

torch.Tensor

In [54]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [55]:
a

tensor([7.8000, 5.0000])

In [56]:
a.new

<function Tensor.new>

In [57]:
a = a.new_ones(6,5, dtype = torch.double)
a

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], dtype=torch.float64)

In [58]:
a = torch.randn_like(a, dtype = torch.float)
a

tensor([[-7.3971e-01, -5.6214e-01, -2.7694e-01, -1.8342e+00,  2.4605e-01],
        [ 4.8770e-01, -6.7844e-01, -1.5103e-01,  3.2183e-01,  1.3671e+00],
        [ 3.5544e-02, -2.4397e+00, -4.6270e-01, -1.1070e+00, -2.1028e-01],
        [ 1.2030e+00,  6.6189e-01,  6.1584e-01,  9.0320e-01,  8.2896e-01],
        [-1.3572e+00, -1.3607e+00,  2.6322e-01,  2.9177e-01, -1.1347e-01],
        [ 4.7198e-01, -1.0529e+00, -2.4265e-03, -3.6633e-01, -2.4381e-01]])

In [59]:
print(a.size())

torch.Size([6, 5])


### Operations

In [60]:
b = torch.rand(6, 5 )
b


tensor([[0.7748, 0.9323, 0.2364, 0.3406, 0.6178],
        [0.8211, 0.8735, 0.8518, 0.4870, 0.1865],
        [0.9125, 0.9134, 0.9884, 0.9301, 0.7459],
        [0.6926, 0.0145, 0.2134, 0.9879, 0.4798],
        [0.2806, 0.1460, 0.8235, 0.4077, 0.8807],
        [0.8413, 0.3469, 0.8994, 0.2344, 0.0872]])

In [61]:
print(a+b)

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])


In [62]:
print(torch.add(a,b))

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])


In [63]:
results = torch.empty(6,5)
results

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])

In [64]:
torch.add(a, b , out = results)
print(results)
## map addition to results

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])


###  : inplace

In [65]:
b+a

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])

In [66]:
b.add_(a) # store the outome of b+a inside b just like b = b+a

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])

In [67]:
b

tensor([[ 0.0351,  0.3702, -0.0405, -1.4936,  0.8638],
        [ 1.3088,  0.1950,  0.7008,  0.8089,  1.5535],
        [ 0.9480, -1.5262,  0.5257, -0.1769,  0.5356],
        [ 1.8956,  0.6764,  0.8292,  1.8911,  1.3087],
        [-1.0765, -1.2147,  1.0868,  0.6994,  0.7672],
        [ 1.3133, -0.7061,  0.8970, -0.1319, -0.1566]])

In [68]:
a

tensor([[-7.3971e-01, -5.6214e-01, -2.7694e-01, -1.8342e+00,  2.4605e-01],
        [ 4.8770e-01, -6.7844e-01, -1.5103e-01,  3.2183e-01,  1.3671e+00],
        [ 3.5544e-02, -2.4397e+00, -4.6270e-01, -1.1070e+00, -2.1028e-01],
        [ 1.2030e+00,  6.6189e-01,  6.1584e-01,  9.0320e-01,  8.2896e-01],
        [-1.3572e+00, -1.3607e+00,  2.6322e-01,  2.9177e-01, -1.1347e-01],
        [ 4.7198e-01, -1.0529e+00, -2.4265e-03, -3.6633e-01, -2.4381e-01]])

In [69]:
a[0]

tensor([-0.7397, -0.5621, -0.2769, -1.8342,  0.2460])

In [70]:
a[0][1]

tensor(-0.5621)

In [72]:
a[: , 4] # all rows and 5th column

tensor([ 0.2460,  1.3671, -0.2103,  0.8290, -0.1135, -0.2438])

### resizing : we can resize or reshape tensor , use tensnor.view for that

In [74]:
a = torch.randn(3,3)
a

tensor([[-1.1811, -0.3263, -2.2102],
        [-0.9338, -0.0875,  0.4582],
        [ 0.7208, -0.5437,  0.4146]])

In [79]:
b=a.view(9) # view data in particular shape
b

tensor([-1.1811, -0.3263, -2.2102, -0.9338, -0.0875,  0.4582,  0.7208, -0.5437,
         0.4146])

In [80]:
c = a.view(-1, 9) # the size -1 is inferred from other dimensions
c

tensor([[-1.1811, -0.3263, -2.2102, -0.9338, -0.0875,  0.4582,  0.7208, -0.5437,
          0.4146]])

In [81]:
print(a.size(), b.size(), c.size())

torch.Size([3, 3]) torch.Size([9]) torch.Size([1, 9])


### Converting torch tensor to Numpy array

In [83]:
x = torch.ones(4)
x

tensor([1., 1., 1., 1.])

In [85]:
y = x.numpy()
y

array([1., 1., 1., 1.], dtype=float32)

#### See how numpy array changed value

In [86]:
x.add_(1)
print(x)
print(y)

tensor([2., 2., 2., 2.])
[2. 2. 2. 2.]


### Converting Numpy array to Torch tensor

In [90]:
import numpy as np
f = np.ones(4)
g = torch.from_numpy(f)
np.add(f, 1 , out=f)
print(f)
print(g)

[2. 2. 2. 2.]
tensor([2., 2., 2., 2.], dtype=torch.float64)


## CUDA Tensors
Tensor can be moved onto any device using the .to method

In [94]:
# Let us run this cell only if CUDA is available
# WE will use 'torch.device' objects to move tensors in and out of GPU


if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device  =device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.to("cpu", torch.double))

## Automatic Differentiation

Definition :
This class is an engine to calculate derivatives. It records the graph of all the operations perfomed on a gradient enabled tensor and creates a acyclic graph called the dynamic computational graph (DCG). The leaves of this graph are input tensors and the root are output tensors. Gradients are calculated by tracing graph from the root to the leaf and multiplying every gradient in the way using chain rule. 