In [1]:
import tensorflow as tf

print("TensorFlow version : {}".format(tf.__version__))
print("Keras version : {}".format(tf.keras.__version__))
 ## version check

TensorFlow version : 2.12.0
Keras version : 2.12.0


### GPU/CPU Check

In [2]:
variable = tf.Variable([3,3])
type(variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [3]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [4]:
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')
    
print(tf.test.is_built_with_gpu_support , tf.test.is_built_with_cuda)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU
<function is_built_with_gpu_support at 0x0000024F6BF2F420> <function is_built_with_cuda at 0x0000024F6BF2F380>


### Tensor Constant

In [5]:
abc = tf.constant(42)
abc

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [6]:
print(abc)
print(variable)

tf.Tensor(42, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>


In [7]:
abc.numpy()

42

In [8]:
abc = tf.constant(1 , dtype = tf.int32)

In [9]:
abc.dtype

tf.int32

In [10]:
abc.numpy()

1

In [11]:
y = tf.constant([[4,2,4],[6,7,9]])

In [12]:
print(y)

tf.Tensor(
[[4 2 4]
 [6 7 9]], shape=(2, 3), dtype=int32)


In [13]:
y.numpy()

array([[4, 2, 4],
       [6, 7, 9]])

In [14]:
y.shape

TensorShape([2, 3])

### Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros

In [15]:
print(tf.ones(shape = (2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [16]:
print(tf.zeros(shape = (2,5)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)


### Tf addition

In [17]:
a = tf.constant([[4,6,7], [8,5,6]])
b = tf.constant([[8,2,4],[9,3,5]])
c = tf.add(a , b)

In [18]:
print(c)

tf.Tensor(
[[12  8 11]
 [17  8 11]], shape=(2, 3), dtype=int32)


### Random constant

In [19]:
tf.random.normal(shape=(2,2), mean= 0 , stddev = 1.0)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.01451947,  0.17228732],
       [-0.39369065,  0.93111414]], dtype=float32)>

### Variables

A variable is a special tensor that os used to store varible values and needs to be initialized with some values, later the values can be changed

In [20]:
var0 = 23 # python variable 
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([[[1,2,3],[4,5,6]], [[3,4,6],[8,9,5]]]) # rank 3 tensor
var0 , var1 , var2

(23,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[3, 4, 6],
         [8, 9, 5]]])>)

### To reassign a variable , use var.assign()

In [21]:
var0 = tf.Variable(88)
var0

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=88>

In [22]:
var0.assign(65)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=65>

In [23]:
b = tf.random.normal(shape = (2,2))
c = tf.Variable(b)
print(b)

tf.Tensor(
[[ 1.096735   -0.42141613]
 [-0.8847096   1.1381403 ]], shape=(2, 2), dtype=float32)


In [24]:
print(c)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.096735  , -0.42141613],
       [-0.8847096 ,  1.1381403 ]], dtype=float32)>


In [25]:
new_value = tf.random.normal(shape = (2,2))
c.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[-1.8574077 ,  1.2808335 ],
       [-1.051336  , -0.36300865]], dtype=float32)>

In [26]:
tf.random.uniform(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.12196088, 0.90470004, 0.735397  ],
       [0.98472214, 0.56903446, 0.23356664]], dtype=float32)>

### shaping a tensor

In [27]:
tensor = tf.Variable([[[10,44,66], [54,23,65]], [[76,98,90],[54,23,54]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

### tensors can be reshaped and retain the same values which is required for constructing neural network

In [28]:
tensor1 = tf.reshape(tensor ,[2,6]) # 2 rows and 6 columns
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 44, 66, 54, 23, 65],
       [76, 98, 90, 54, 23, 54]])>

In [29]:
tensor2 = tf.reshape(tensor, [1,12])
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[10, 44, 66, 54, 23, 65, 76, 98, 90, 54, 23, 54]])>

### Rank of tensor

Rank of tensor is defined as thenumver of dimensions , which is the number of indices that are required to cpecify any particular element of that tensor

In [30]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

In [31]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [32]:
tensor[0][1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([54, 23, 65])>

In [33]:
tensor3 = tensor[1,0,2] # slikece 1 , row1 , column2 
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=90>

### creating a tensor to NumPy variable

In [34]:
print(tensor.numpy())

[[[10 44 66]
  [54 23 65]]

 [[76 98 90]
  [54 23 54]]]


In [35]:
print(tensor[1,0,2].numpy())

90


### finding the size or length of a tensor

In [36]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

### TensorFlow Mathematical Operations

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU

In [37]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c) 

print(a)
print(b)
print(c)
print(d)
print(e)


tf.Tensor(
[[-1.4412049  -0.5903153 ]
 [-0.19236733  0.79838926]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.18932353  1.7453884 ]
 [ 1.1281312  -1.027294  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-1.2518814   1.1550732 ]
 [ 0.93576384 -0.22890478]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[1.567207  1.3341941]
 [0.875654  0.0523974]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.28596628 3.1742556 ]
 [2.5491598  0.79540426]], shape=(2, 2), dtype=float32)


### Performing element-wise primitive tensor operations

In [38]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 100, 1936, 4356],
        [2916,  529, 4225]],

       [[5776, 9604, 8100],
        [2916,  529, 2916]]])>

In [39]:
## broadcast.... perform action on every element

tensor4 = tensor*4
tensor4.numpy()

array([[[ 40, 176, 264],
        [216,  92, 260]],

       [[304, 392, 360],
        [216,  92, 216]]])

In [40]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

### Transpose matrix multiplication

In [41]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u , tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [42]:
i = tf.cast(tensor1 , dtype=tf.int32)

In [43]:
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 44, 66, 54, 23, 65],
       [76, 98, 90, 54, 23, 54]])>

### casting with truncation

In [44]:
j = tf.cast(tf.constant(4.9), dtype =tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Ragged tensors

a ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various length. There are variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.

Below example shows how to declare a constant ragged array

In [45]:
ragged = tf.ragged.constant([[9,7,4,3],[],[11,12,8],[3],[7,8]])

In [46]:
ragged

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>

In [47]:
ragged[0,:]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 7, 4, 3])>

In [48]:
ragged[1, :]

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [49]:
ragged[2, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12,  8])>

### squarred differencce of tensors

In [50]:
varx = [4,5,6,1,2,]
vary = 8
varz = tf.math.squared_difference(varx,vary)

In [51]:
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

### calculate the mean 
 tf.reduce_mean()
 <br> Similar to np.mean , exceot that it infere the return datatype from the input tensor , whereas np.mean allows you to specify the output type

In [52]:
numbers = tf.constant([[8.,9.],[1.,2.]])


### calculate mean accross all axes

In [53]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

### calculate the mean across colmns (reduce rows) with this:

In [54]:
tf.reduce_mean(input_tensor=numbers , axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

### whenkeepdims = True

In [55]:
tf.reduce_mean(input_tensor = numbers , axis = 0 , keepdims = True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

### create normal distribution random data

In [56]:
tf.random.normal(shape = (3,2), mean = 10 , stddev = 2, dtype = tf.float32 , seed = None , name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[12.505567, 10.456968],
       [10.728312, 13.067928],
       [10.684299, 11.12365 ]], dtype=float32)>

In [57]:
# seed is random state
tf.random.set_seed(11)
tf.random.normal(shape = (3,2), mean = 10 , stddev = 2, dtype = tf.float32 , seed = True , name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11.914958, 10.347397],
       [ 8.03833 ,  9.807295],
       [ 9.834548, 11.845785]], dtype=float32)>

### Practical example of Random values using dices

In [58]:
dice11 = tf.Variable(tf.random.uniform([10,1], minval = 1 , maxval = 7 , dtype = tf.int32))
dice12 = tf.Variable(tf.random.uniform([10,1], minval = 1 , maxval = 7 , dtype = tf.int32))

# lets add

dice_sum1 = dice11 + dice12
final_matrix = tf.concat(values = [dice11, dice12 , dice_sum1], axis = 1)
final_matrix.numpy()

array([[ 5,  4,  9],
       [ 1,  4,  5],
       [ 2,  2,  4],
       [ 3,  5,  8],
       [ 3,  1,  4],
       [ 1,  4,  5],
       [ 3,  6,  9],
       [ 2,  4,  6],
       [ 5,  6, 11],
       [ 1,  3,  4]])

## Finding the indices of the largest and smallest element

 It will always show you indexes in result

In [59]:
tensor_1d = tf.constant([2,4,2,1,11,4,45,767,68,3,455,223,-30])
i = tf.argmax(input = tensor_1d)
i
# showing index of largest element

<tf.Tensor: shape=(), dtype=int64, numpy=7>

### Saving and restoring using a Checkpoint
We can create restore point for our model training , if our system crashes , model training will start from checkpoint

In [60]:
variable1 = tf.Variable([[5,6,9,4],[12,15,16,18]])
checkpoint = tf.train.Checkpoint(var=variable1)
savepath = checkpoint.save('./vars')
variable1.assign([[0,0,0,0],[0,0,0,0]])
checkpoint.restore(savepath)

# we can see files created in project folder

### tf.function()

In [61]:

def f1(x,y):
    return tf.reduce_mean(input_tensor = tf.multiply(x**3 , 6) + y**3)

In [63]:
func = tf.function(f1)

x = tf.constant([3.,-4.])
y = tf.constant([1.,4.])

f1(x,y).numpy()

-78.5

In [64]:
func(x,y).numpy()

-78.5

## Calculate gradient

### Gradient tape
Another differnece from numpy is that it can automatically track the gradient of any variable.<br>

Open one GradientTape and tape.watch() tack variables through

It will tape all the changes while doing dy/dx to the variables

In [71]:
a = tf.random.normal(shape = (2,2))
b = tf.random.normal(shape = (2,2))
with tf.GradientTape() as tape:
    tape.watch(a)
    c = tf.sqrt(tf.square(a)+ tf.square(b))
    dc_da = tape.gradient(c , a)
    print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


For all varibles , the calculation is tracked by default and used to find the gradient, so do not usetape.watch()

In [73]:
a = tf.Variable(a)
with tf.GradientTape() as tape:
    c = tf.sqrt(tf.square(a)+ tf.square(b))
    tc_da = tape.gradient(c, a)
    print(dc_da)

tf.Tensor(
[[-0.96916884  0.10584572]
 [ 0.12097336 -0.5725143 ]], shape=(2, 2), dtype=float32)


## Using Sequential model

Firstly , you cam pass a list of layer instances to the constructor , as in the following example . for now , we will jusr exmplain enough to allow you to what is happening here. <br>

Acquire the data. MNIST is dataset of hand-drawn numerals , each on a 28 x 28 pixel grid. Every individual data point is an unsigned 8 bit integer (uint8) , as are the labels

In [74]:
# loading the dataset
mnist_data = tf.keras.datasets.mnist
(train_x, train_y), (test_x, test_y) = mnist_data.load_data()

11490434/11490434 [==============================] - 1s 0us/step


In [78]:
train_y

<tf.Tensor: shape=(60000,), dtype=int64, numpy=array([5, 0, 4, ..., 5, 6, 8], dtype=int64)>

### Defining Variables

In [75]:
epochs = 10 
batch_size = 32

In [77]:
# normalize all the data points and cast the labels to int64
train_x , test_x = tf.cast(train_x/255.0 , tf.float32) , tf.cast(test_x/255.0 , tf.float32)
train_y , test_y = tf.cast(train_y , tf.int64) , tf.cast(test_y , tf.int64)

### Building the Architencture

In [80]:
mnistmodel1 = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512 , activation = tf.nn.relu),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation= tf.nn.softmax)
])

### compiling model

In [81]:
optimiser = tf.keras.optimizers.Adam()
mnistmodel1.compile(optimizer=optimiser , loss = 'sparse_categorical_crossentropy', metrics = ['accuracy'])

### Fitting the model

In [82]:
mnistmodel1.fit(train_x , train_y , batch_size=32 , epochs = 5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.2177 - accuracy: 0.9354
Epoch 2/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0981 - accuracy: 0.9702
Epoch 3/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0690 - accuracy: 0.9789
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0540 - accuracy: 0.9827
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0434 - accuracy: 0.9863


### Evaluate model

In [83]:
mnistmodel1.evaluate(test_x , test_y)

313/313 [==============================] - 0s 894us/step - loss: 0.0620 - accuracy: 0.9818


[0.06195680424571037, 0.9818000197410583]

### loss is 0.06 on test dataset and accuracy is 0.98

In [85]:
mnistmodel1.predict(test_x)

313/313 [==============================] - 0s 1ms/step


array([[1.90531409e-07, 6.02602412e-09, 5.61604793e-07, ...,
        9.99918938e-01, 1.99167332e-08, 1.76651592e-05],
       [2.54929478e-09, 6.98360267e-08, 9.99999762e-01, ...,
        2.90622828e-15, 1.25290143e-07, 7.79702027e-14],
       [4.16870671e-09, 9.99900818e-01, 3.88439366e-06, ...,
        4.55332838e-06, 8.86398775e-05, 4.08849949e-08],
       ...,
       [1.35022261e-14, 3.73407295e-12, 2.30448527e-14, ...,
        5.16832266e-08, 4.18603392e-08, 1.82525746e-05],
       [1.03538504e-10, 4.52188607e-13, 4.12159049e-14, ...,
        2.29580330e-12, 1.99665578e-06, 5.24916265e-13],
       [7.13293513e-09, 5.32983014e-14, 4.64482591e-10, ...,
        4.76251157e-16, 3.37243816e-10, 3.37137788e-13]], dtype=float32)

### Save model

In [89]:
tf.saved_model.save(mnistmodel1 , export_dir='./assets/')

INFO:tensorflow:Assets written to: ./assets/assets


INFO:tensorflow:Assets written to: ./assets/assets
