In [3]:
import tensorflow as tf

print("TensorFlow version : {}".format(tf.__version__))
print("Keras version : {}".format(tf.keras.__version__))
 ## version check

TensorFlow version : 2.12.0
Keras version : 2.12.0


### GPU/CPU Check

In [4]:
variable = tf.Variable([3,3])
type(variable)

tensorflow.python.ops.resource_variable_ops.ResourceVariable

In [5]:
variable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>

In [6]:
if tf.test.is_gpu_available():
    print('GPU')
    print('GPU #0')
    print(var.device.endswith('GPU:0'))
else:
    print('CPU')
    
print(tf.test.is_built_with_gpu_support , tf.test.is_built_with_cuda)

Instructions for updating:
Use `tf.config.list_physical_devices('GPU')` instead.
CPU
<function is_built_with_gpu_support at 0x0000020A40EF5580> <function is_built_with_cuda at 0x0000020A40EF54E0>


### Tensor Constant

In [7]:
abc = tf.constant(42)
abc

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [8]:
print(abc)
print(variable)

tf.Tensor(42, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([3, 3])>


In [9]:
abc.numpy()

42

In [10]:
abc = tf.constant(1 , dtype = tf.int32)

In [11]:
abc.dtype

tf.int32

In [12]:
abc.numpy()

1

In [13]:
y = tf.constant([[4,2,4],[6,7,9]])

In [14]:
print(y)

tf.Tensor(
[[4 2 4]
 [6 7 9]], shape=(2, 3), dtype=int32)


In [15]:
y.numpy()

array([[4, 2, 4],
       [6, 7, 9]])

In [16]:
y.shape

TensorShape([2, 3])

### Commonly used method is to generate constant tf.ones and tf.zeros like of numpy np.ones and np.zeros

In [17]:
print(tf.ones(shape = (2,3)))

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [18]:
print(tf.zeros(shape = (2,5)))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(2, 5), dtype=float32)


### Tf addition

In [19]:
a = tf.constant([[4,6,7], [8,5,6]])
b = tf.constant([[8,2,4],[9,3,5]])
c = tf.add(a , b)

In [20]:
print(c)

tf.Tensor(
[[12  8 11]
 [17  8 11]], shape=(2, 3), dtype=int32)


### Random constant

In [21]:
tf.random.normal(shape=(2,2), mean= 0 , stddev = 1.0)


<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.08033521,  0.3332375 ],
       [ 2.3201346 ,  0.8406601 ]], dtype=float32)>

### Variables

A variable is a special tensor that os used to store varible values and needs to be initialized with some values, later the values can be changed

In [22]:
var0 = 23 # python variable 
var1 = tf.Variable(42) # rank 0 tensor
var2 = tf.Variable([[[1,2,3],[4,5,6]], [[3,4,6],[8,9,5]]]) # rank 3 tensor
var0 , var1 , var2

(23,
 <tf.Variable 'Variable:0' shape=() dtype=int32, numpy=42>,
 <tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
 array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[3, 4, 6],
         [8, 9, 5]]])>)

### To reassign a variable , use var.assign()

In [23]:
var0 = tf.Variable(88)
var0

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=88>

In [24]:
var0.assign(65)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=65>

In [25]:
b = tf.random.normal(shape = (2,2))
c = tf.Variable(b)
print(b)

tf.Tensor(
[[-0.9868238  -0.26500618]
 [-2.1089494  -0.15782888]], shape=(2, 2), dtype=float32)


In [26]:
print(c)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.9868238 , -0.26500618],
       [-2.1089494 , -0.15782888]], dtype=float32)>


In [27]:
new_value = tf.random.normal(shape = (2,2))
c.assign(new_value)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=float32, numpy=
array([[ 0.31961676,  1.6973215 ],
       [ 0.05535975, -0.3930196 ]], dtype=float32)>

In [28]:
tf.random.uniform(shape = (2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.995294  , 0.02946353, 0.13671172],
       [0.41596723, 0.38771808, 0.81382   ]], dtype=float32)>

### shaping a tensor

In [30]:
tensor = tf.Variable([[[10,44,66], [54,23,65]], [[76,98,90],[54,23,54]]])
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

### tensors can be reshaped and retain the same values which is required for constructing neural network

In [32]:
tensor1 = tf.reshape(tensor ,[2,6]) # 2 rows and 6 columns
tensor1

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 44, 66, 54, 23, 65],
       [76, 98, 90, 54, 23, 54]])>

In [33]:
tensor2 = tf.reshape(tensor, [1,12])
tensor2

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[10, 44, 66, 54, 23, 65, 76, 98, 90, 54, 23, 54]])>

### Rank of tensor

Rank of tensor is defined as thenumver of dimensions , which is the number of indices that are required to cpecify any particular element of that tensor

In [34]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

In [44]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [38]:
tensor[0][1]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([54, 23, 65])>

In [39]:
tensor3 = tensor[1,0,2] # slikece 1 , row1 , column2 
tensor3

<tf.Tensor: shape=(), dtype=int32, numpy=90>

### creating a tensor to NumPy variable

In [45]:
print(tensor.numpy())

[[[10 44 66]
  [54 23 65]]

 [[76 98 90]
  [54 23 54]]]


In [46]:
print(tensor[1,0,2].numpy())

90


### finding the size or length of a tensor

In [47]:
tensor_size = tf.size(input=tensor).numpy()
tensor_size

12

### TensorFlow Mathematical Operations

Can be used as numpy for artificial operations. Tensorflow can not execute these operations on the GPU or TPU

In [51]:
a = tf.random.normal(shape=(2,2))
b = tf.random.normal(shape=(2,2))
c = a+b
d = tf.square(c)
e = tf.exp(c) 

print(a)
print(b)
print(c)
print(d)
print(e)


tf.Tensor(
[[-1.4648411   0.28415474]
 [ 0.40278956  4.5492496 ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.7698339   0.47598928]
 [ 2.1425858  -0.51791817]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.6950072  0.760144 ]
 [ 2.5453753  4.0313315]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.48303503  0.5778189 ]
 [ 6.4789357  16.251635  ]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 0.49907085  2.1385841 ]
 [12.748012   56.335873  ]], shape=(2, 2), dtype=float32)


### Performing element-wise primitive tensor operations

In [52]:
tensor*tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 100, 1936, 4356],
        [2916,  529, 4225]],

       [[5776, 9604, 8100],
        [2916,  529, 2916]]])>

In [53]:
## broadcast.... perform action on every element

tensor4 = tensor*4
tensor4.numpy()

array([[[ 40, 176, 264],
        [216,  92, 260]],

       [[304, 392, 360],
        [216,  92, 216]]])

In [54]:
tensor

<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[10, 44, 66],
        [54, 23, 65]],

       [[76, 98, 90],
        [54, 23, 54]]])>

### Transpose matrix multiplication

In [55]:
matrix_u = tf.constant([[6,7,6]])
matrix_v = tf.constant([[3,4,3]])
tf.matmul(matrix_u , tf.transpose(a=matrix_v))

<tf.Tensor: shape=(1, 1), dtype=int32, numpy=array([[64]])>

### Casting a tensor to another datatype

In [57]:
i = tf.cast(tensor1 , dtype=tf.int32)

In [58]:
i

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[10, 44, 66, 54, 23, 65],
       [76, 98, 90, 54, 23, 54]])>

### casting with truncation

In [60]:
j = tf.cast(tf.constant(4.9), dtype =tf.int32)
j

<tf.Tensor: shape=(), dtype=int32, numpy=4>

### Ragged tensors

a ragged tensor is a tensor having one or more ragged dimensions. Ragged dimensions are dimensions that have slices having various length. There are variety of methods for the declaration of ragged arrays, the simplest way is declaring a constant ragged array.

Below example shows how to declare a constant ragged array

In [61]:
ragged = tf.ragged.constant([[9,7,4,3],[],[11,12,8],[3],[7,8]])

In [65]:
ragged

<tf.RaggedTensor [[9, 7, 4, 3], [], [11, 12, 8], [3], [7, 8]]>

In [68]:
ragged[0,:]

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([9, 7, 4, 3])>

In [69]:
ragged[1, :]

<tf.Tensor: shape=(0,), dtype=int32, numpy=array([], dtype=int32)>

In [70]:
ragged[2, :]

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 12,  8])>

### squarred differencce of tensors

In [71]:
varx = [4,5,6,1,2,]
vary = 8
varz = tf.math.squared_difference(varx,vary)

In [72]:
varz

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([16,  9,  4, 49, 36])>

### calculate the mean 
 tf.reduce_mean()
 <br> Similar to np.mean , exceot that it infere the return datatype from the input tensor , whereas np.mean allows you to specify the output type

In [73]:
numbers = tf.constant([[8.,9.],[1.,2.]])


### calculate mean accross all axes

In [74]:
tf.reduce_mean(input_tensor=numbers)

<tf.Tensor: shape=(), dtype=float32, numpy=5.0>

### calculate the mean across colmns (reduce rows) with this:

In [75]:
tf.reduce_mean(input_tensor=numbers , axis = 0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([4.5, 5.5], dtype=float32)>

### whenkeepdims = True

In [77]:
tf.reduce_mean(input_tensor = numbers , axis = 0 , keepdims = True)

<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[4.5, 5.5]], dtype=float32)>

### create normal distribution random data

In [88]:
tf.random.normal(shape = (3,2), mean = 10 , stddev = 2, dtype = tf.float32 , seed = None , name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 7.2225695,  8.269536 ],
       [10.729671 ,  7.804965 ],
       [ 9.821513 , 14.872856 ]], dtype=float32)>

In [92]:
# seed is random state
tf.random.set_seed(11)
tf.random.normal(shape = (3,2), mean = 10 , stddev = 2, dtype = tf.float32 , seed = True , name = None)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[11.914958, 10.347397],
       [ 8.03833 ,  9.807295],
       [ 9.834548, 11.845785]], dtype=float32)>

### Practical example of Random values using dices

In [96]:
dice11 = tf.Variable(tf.random.uniform([10,1], minval = 1 , maxval = 7 , dtype = tf.int32))
dice12 = tf.Variable(tf.random.uniform([10,1], minval = 1 , maxval = 7 , dtype = tf.int32))

# lets add

dice_sum1 = dice11 + dice12
final_matrix = tf.concat(values = [dice11, dice12 , dice_sum1], axis = 1)
final_matrix.numpy()

array([[ 5,  3,  8],
       [ 2,  4,  6],
       [ 2,  1,  3],
       [ 4,  5,  9],
       [ 1,  6,  7],
       [ 5,  6, 11],
       [ 1,  6,  7],
       [ 3,  1,  4],
       [ 5,  6, 11],
       [ 6,  4, 10]])